### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by vnijs** [rstudio/sortable#1]
Wow! Really nice! It works in the sidebarPanel too! See below.

Can you move elements between containers, ala, rpivotTable? Also, is there a way to access the sorting information? Could a cool way to customize a GUI. 

``` r
library(shiny)
library(sortableR)

# Define UI for random distribution application
shinyUI(fluidPage(

  # Application title
  titlePanel("Tabsets"),

  # Sidebar with controls to select the random distribution type
  # and number of observations to generate. Note the use of the
  # br() element to introduce extra vertical spacing
  sidebarLayout(
    sidebarPanel(id = "sortSidebar",
      radioButtons("dist", "Distribution type:",
                   c("Normal" = "norm",
                     "Uniform" = "unif",
                     "Log-normal" = "lnorm",
                     "Exponential" = "exp")),
      br(),

      sliderInput("n",
                  "Number of observations:",
                   value = 500,
                   min = 1,
                   max = 1000)
    ),

    # Show a tabset that includes a plot, summary, and table view
    # of the generated distribution
    mainPanel(
      tabsetPanel(type = "tabs", id = "sortTab",
        tabPanel("Plot", plotOutput("plot")),
        tabPanel("Summary", verbatimTextOutput("summary")),
        tabPanel("Table", tableOutput("table"))
      )
    )
  )
  ,sortableR("sortSidebar")
  ,sortableR("sortTab")
))
```

**Comment by mostly-harmless** [comment]
Your first shiny example shows that you can access the sorting information. Can you aldo _set_ the order, ala update...Input in shiny.

**Comment by happyshows** [comment]
up for @vnijs idea. I'm wondering if shiny can "read" the dragged values in boxes so that when this is applied in rendering a chart, it would be a smoother experience for user to drag and drop the dimensions for a diagram.

**Comment by Cat1796** [comment]
This is indeed really a fantastic widget. I do miss one last link to be perfect in shiny, as mentioned above, and as shown in your example, one can access the values using this.el.textcontent. This is nevertheless not ideal as it is very verbose. I would really like to be able to access the ids of the sorted elements. Would you know how to do this?

**Comment by timelyportfolio** [comment]
@Cat1796, so glad you found it and happy to hear your interest.  Since I built this as part of my htmlwidget-per-week project, I did not have much time to fully develop it back then, and have focused on some of the more popular widgets since then.  I'll have a look, and if nothing else update the underlying dependencies.

**Comment by andrie** [comment]
I also think this is "wow!" and have made additional improvements to the original idea by @timelyportfolio.

The `sortable_item()` function now captures the input and makes this available to a shiny app.  (See examples in updated Readme).  Also, we (@schloerke and I) are working on exposing `sortable` as a custom question type for `learnr`.  So expect quite a bit of activity in this package for the next few weeks.

Closing this issue, but please take the new code for a test drive and let us know what you think.
