### ISSUE TITLE
Multi-drag for bucklist

### ISSUE THREAD

**Issue by NetZissou** [rstudio/sortable#102]
Hi, I tried to specify `options = sortable::sortable_options(multiDrag = TRUE)`  but it's not working. Is there a workaround for dragging multiple items at once? Thanks!

**Comment by andrie** [comment]
I've just tried the example with `multiDrag = TRUE` and it works as expected.

https://github.com/rstudio/sortable/blob/main/inst/examples/example_rank_list_multidrag.R
