### ISSUE TITLE
On-Click

### ISSUE THREAD

**Issue by corey-dawson** [rstudio/sortable#103]
Hello, 
I was wondering if there is a simple "on-click" listener? I would like to have create a sortable list where a user could click the card to get more information (maybe via a shinyalert or modal), and also drag the card to re-order. The listener could return the text on the card that was clicked perhaps.
Thanks in advance,
Corey

**Comment by andrie** [comment]
You can find the documentation for the `SortableJS` library at https://github.com/SortableJS/Sortable

The `onChoose` event might be what you're looking for.
