### ISSUE TITLE
Error in &&: 'length = 3' in coercion to 'logical(1)'  on rank_list function

### ISSUE THREAD

**Issue by FarhanShahJahan** [rstudio/sortable#106]
Got this error when update my R version to 4.3.1

**Comment by andrie** [comment]
Can you please add a minimal reproducible example?

I've just updated to R-4.3.1, ran all the tests and can't replicate your problem.

**Comment by FarhanShahJahan** [comment]
Solved it, the error message mislead me.

BTW, the error is on the title, it can accept styling like the previous version

```
      #text = span(content_text, style = "font-weight:500; color:#333 !important;"),
      text = content_text, 
```

**Comment by pisistrato** [comment]
I would like to re-open this.
With R 4.4.1 I am getting this error with
```
bucket_list(
    header = "Example",
    add_rank_list(
        input_id = "id",
        text = div("text"),
        labels = "label"))
```
It was working fine in previous R versions (e.g. 4.1.1). The error is due to the `div()`
