### ISSUE TITLE
Unable to drop elements (novel_solutions example)

### ISSUE THREAD

**Issue by johannes-titz** [rstudio/sortable#109]
I experience problems with dropping items for more complex setups. To reproduce it, you can use the example from your vignette: https://cran.r-project.org/web/packages/sortable/vignettes/novel_solutions.html

When I run this locally, I can drag elements, but cannot drop them inside the panels on the right-hand side. Does it still work for you? I have R 4.3.2, all packages up to date, running Arch and an up to date chromium browser.

Maybe this is related to #108 

Edit: I confirmed that this still works with htmlwidgets 1.6.2

**Comment by andrie** [comment]
This seems related to #108, as you point out.
