### ISSUE TITLE
Move repo to rstudio's GitHub team and update Authors@R

### ISSUE THREAD

**Issue by schloerke** [rstudio/sortable#11]
* Would give the education team admin rights for things like PR reviews and travis easier.  Would make submissions to CRAN cleaner.

- [ ] Before next CRAN submission get Kent's approval of progress in package
- [ ] Add person role of `cre` (Maintainer) for Andrie
- [ ] Add person role for Kent of `ccp` and note that Kent is `original author`
> Conceptor [ccp]
>   A person or organization responsible for the original idea on which a work is based, this includes the scientific author of an audio-visual item and the conceptor of an advertisement

cc @timelyportfolio @andrie

**Comment by timelyportfolio** [comment]
Happy to do this.  Glad to see this incorporated and developed fully!

**Comment by andrie** [comment]
Thanks to the goodwill of @timelyportfolio, this repo has now been migrated to https://github.com/rstudio/sortable.

(Note also the name change to `sortable`, whereas previously it was `sortableR`.)
