### ISSUE TITLE
"d.call" is not a function in browser console

### ISSUE THREAD

**Issue by CAM-E-L** [rstudio/sortable#110]
Hello,

a collegue is experiecing some problems using "sortable" within a Shiny application. 

We reinstalled R packages / did updates / tried to include the JS library of sortable in shiny manually, but nothing worked. We get the following error message in the browser console:

"d.call" is not a function; see Screenshot:
![Screenshot_sortable](https://github.com/rstudio/sortable/assets/128906295/1854f6d4-bb5d-44d4-9402-ebbfd81b5fcd)

Thanks for your help!

**Comment by andrie** [comment]
This is going to be very difficult to troubleshoot, since I have no information about your app.

Is there any way you can make a minimal, reproducible example of a shiny app that throws this error?

**Comment by andrie** [comment]
If you can provide a minimal reproducible example, please attach and re-open the issue.
