### ISSUE TITLE
onLoad fires too eagerly

### ISSUE THREAD

**Issue by colearendt** [rstudio/sortable#36]
Related to #34 

It seems that `onLoad` fires more eagerly than it should? It seems to fire twice on initialization and on every `onSort`, at least so far as I can tell. Is this the expected behavior?

```
rank_list(
        text = "List 1",
        input_id = session$ns("list_1"),
        labels = data_1(),
        options = sortable_options(
          group = "my-test",
          onLoad = htmlwidgets::JS("function(evt) { console.log('hello'); }"),
          onSort = htmlwidgets::JS("function(evt) { console.log('hello - sort'); }")
        )
      )
```

![image](https://user-images.githubusercontent.com/23075542/62015617-2ae11a80-b17b-11e9-8884-169fce406b91.png)

**Comment by schloerke** [comment]
No. It is not expected. I am only called it once.

I will look into this.

**Comment by schloerke** [comment]
I can not reproduce given the `rank_list` code above. (It is behaving as expected.)

Can I have your full app?

--------------

My self contained test

```r
rank_list(
  text = "List 1",
  input_id = "barret",
  labels = LETTERS[1:5],
  options = sortable_options(
    group = "my-test",
    onLoad = htmlwidgets::JS("function(evt) { console.log('calling onLoad', evt); }"),
    onSort = htmlwidgets::JS("function(evt) { console.log('calling onSort', evt); }")
  )
)
```

**Comment by colearendt** [comment]
Thanks for clarifying, and apologies for my shortsightedness here. I thought I had a grasp of some of the other reactive stuff I was doing, but this is my fault.

It makes sense that `renderUI` + changing the labels would contribute to a fully regenerated object, which is what I am experiencing here.
