### ISSUE TITLE
Need a way to update the labels in rank_list

### ISSUE THREAD

**Issue by quantitative-technologies** [rstudio/sortable#47]
For my app, I need a `rank_list` where the labels are determined at run-time. However, it only seems to be able to handle a character vector that is defined before the app starts. 

Is there a way to update the labels of a `rank_list`?

**Comment by andrie** [comment]
It sounds to me you want to build a [dynamic UI](https://shiny.rstudio.com/articles/dynamic-ui.html).

I suspect that `rank_list()` is not different from any other Shiny object, and hopefully the article points you in the right direction.

**Comment by quantitative-technologies** [comment]
Yes, that was what I needed. It works fine with `rank_list()`.
