### ISSUE TITLE
Change options

### ISSUE THREAD

**Issue by KZARCA** [rstudio/sortable#64]
Hi,
I would like to disable items of bucket_list when a condition is TRUE.
I tried to find the variable in the JS side via the debugging tool on my browser, but I'm lost. 
What would be the proper way to do it? 
Best

**Comment by andrie** [comment]
I think the way to do this is to modify the UI on the `shiny` side, i.e. in R code, similar to the idea described in #66 

You may have to use a combination of `observeEvent()` and `uiOutput()` to achieve this.
