### ISSUE TITLE
Update sortable.js to version 1.13.0

### ISSUE THREAD

**Issue by msaltieri** [rstudio/sortable#73]
Are you planning to update `sortable.js` to its latest version? It might help to fix the loss of drag event bug on Safari 13, as explained in [this issue](https://github.com/SortableJS/Sortable/issues/1571).

Is there another way to use current version of `sortable` with v1.13.0? of `sortable.js`?

**Comment by andrie** [comment]
Thanks for reporting.  It's quite straight-forward to include a new version of `sortable.js` and I've created a branch called `sortablejs-1.13` and a PR #74 to test this.

Please can you checkout this branch and let me know if everything works as expected?

```r
remotes::install_github("rstudio/sortable@sortablejs-1.13")
```

**Comment by msaltieri** [comment]
Hi @andrie thanks for your quick answer. I've just tested your `sortablejs-1.13` branch and I can confirm the loss of drag event bug is **fixed**.

Are you planning to release a new version of `sortable` with this enhancement?

**Comment by andrie** [comment]
I didn't have plans to release a new version, but this upgrade would be a good reason to accelerate creating a new version.

Thanks for testing :-)

**Comment by msaltieri** [comment]
If I can help testing or writing part of the code, just get in touch. It would be a pleasure.
