### ISSUE TITLE
Create a "matching" learnR question type

### ISSUE THREAD

**Issue by wrightrc** [rstudio/sortable#76]
Does a matching question type exist yet? 

I have made matching questions with `question_rank` using a bulleted list in the `text` argument, but I think the vertical arrangement is awkward and adds cognitive burden. Left-right arrangement, per traditional matching questions, would be better. I could see this being put together either using a paired bucketlist or a static list on the left and a sortable on the right. 

I may give this a go myself, if there's interest and I can find some time this semester.

**Comment by andrie** [comment]
This seems related to #92

**Comment by andrie** [comment]
@wrightrc , please let me know if the PR in #94 is going in the right direction.  Does this do what you need?

**Comment by andrie** [comment]
It's not clear to me what a "matching" question type would do, but I've just enabled horizontal rank lists. Since this seems to have been the blocker, I'm closing this issue.

Feel free to re-open with additional information.

**Comment by wrightrc** [comment]
Yes #94 looks like it will pair perfectly with a table to make a matching question. Thank you so much @andrie!
