### ISSUE TITLE
Using the latest features from SortableJS

### ISSUE THREAD

**Issue by pepijn-devries** [rstudio/sortable#82]
I'm using the latest version of sortable on CRAN. This version does not seem to support the most recent features present in SortableJS, such as the option 'avoidImplicitDeselect'. Would it be possible to merge this project with the latest version of SortableJS, which should make those features available? Many thanks in advance!

**Comment by andrie** [comment]
Thanks for the suggestion.  I've updated the dev version to include `sortable.js` version 1.14.0 in 8156bcec49eb942e5686a2d6deff58c437f07e08

Please try this and let me know if this works for you.

**Comment by pepijn-devries** [comment]
Thank you for the quick response and action. After a closer inspection I've noticed that the features that I would like to use are included in the master branch of SortableJS, but are not yet released. I will contact the maintainer. Hopefully he is willing to prepare a new release.
