### ISSUE TITLE
Tutorial metadata

### ISSUE THREAD

**Issue by bangecon** [rstudio/sortable#87]
This may seem like a trivial question, but I'm having trouble finding help reordering the yaml keys so that the author name (or subtitle or date) appears above the table of contents in your tutorial like it does in the link to your tutorial for this package (https://andrie-de-vries.shinyapps.io/sortable_tutorial_question_rank/). Even when I copy your markdown code and run it locally, it bumps your name and the date to below the contents! 

I tried fishing around in the CSS and JS files in the learner template a little but didn't have much success and didn't want to mess with it too much.

**Comment by andrie** [comment]
It seems to me that something changed in the `learnr` output format.  If I run my own example now, then I observe the same behaviour.

I suggest you post this as an issue at the `learnr` repo.

Ahah.  I notice you already did that at https://github.com/rstudio/sortable/issues/87

Closing here.
